const likelist = [
    "Zero Two",
    "Rem",
    "Megumin",
    "Mai Sakurajima",
    "Nezuko Kamado",
    "Mikasa Ackerman",
    "Asuna",
    "Rias Gremory",
    "Hange Zoë",
    "Saber",
    "Chika Fujiwara",
    "Hatsune Miku",
    "Yumeko Jabami",
    "Emilia",
    "Bongo",
    "Aqua",
    "Violet Evergarden",
    "Albedo",
    "Akame",
    "Himiko Toga",
    "Shinobu Kochou",
    "Kaguya Shinomiya",
    "Ram",
    "Kirby",
    "Miku Nakano",
    "Shiro",
    "Rin Tohsaka",
    "Kanna Kamui",
    "Akeno Himejima",
    "Ai Hayasaka",
    "Hinata Hyuuga",
    "Raphtalia",
    "Kurumi Tokisaki",
    "Rikka Takanashi",
    "Esdeath",
    "Sinon",
    "Chiaki Nanami",
    "Darkness",
    "Neferpitou",
    "Nami",
    "Tohru",
    "Nino Nakano",
    "Chizuru Ichinose",
    "Ochako Uraraka",
    "Erza Scarlet"
];

module.exports = likelist;